# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManualEntryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manualEntryWindow(object):
    def setupUi(self, manualEntryWindow):
        manualEntryWindow.setObjectName("manualEntryWindow")
        manualEntryWindow.resize(527, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(manualEntryWindow.sizePolicy().hasHeightForWidth())
        manualEntryWindow.setSizePolicy(sizePolicy)
        manualEntryWindow.setMinimumSize(QtCore.QSize(527, 563))
        manualEntryWindow.setMaximumSize(QtCore.QSize(527, 563))
        manualEntryWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line = QtWidgets.QFrame(manualEntryWindow)
        self.line.setGeometry(QtCore.QRect(10, 50, 491, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(manualEntryWindow)
        self.label_2.setGeometry(QtCore.QRect(12, 12, 503, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../logo/e-triage_manual_entry_form.png"))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(manualEntryWindow)
        self.widget.setGeometry(QtCore.QRect(12, 70, 491, 435))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nameLabel = QtWidgets.QLabel(self.widget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.tcLabel = QtWidgets.QLabel(self.widget)
        self.tcLabel.setObjectName("tcLabel")
        self.gridLayout_2.addWidget(self.tcLabel, 2, 0, 1, 1)
        self.diastBPLabel = QtWidgets.QLabel(self.widget)
        self.diastBPLabel.setObjectName("diastBPLabel")
        self.gridLayout_2.addWidget(self.diastBPLabel, 8, 0, 1, 1)
        self.spo2Label = QtWidgets.QLabel(self.widget)
        self.spo2Label.setObjectName("spo2Label")
        self.gridLayout_2.addWidget(self.spo2Label, 6, 0, 1, 1)
        self.sysBPLabel = QtWidgets.QLabel(self.widget)
        self.sysBPLabel.setObjectName("sysBPLabel")
        self.gridLayout_2.addWidget(self.sysBPLabel, 9, 0, 1, 1)
        self.ageLabel = QtWidgets.QLabel(self.widget)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout_2.addWidget(self.ageLabel, 3, 0, 1, 1)
        self.genderLabel = QtWidgets.QLabel(self.widget)
        self.genderLabel.setObjectName("genderLabel")
        self.gridLayout_2.addWidget(self.genderLabel, 4, 0, 1, 1)
        self.heartRateLabel = QtWidgets.QLabel(self.widget)
        self.heartRateLabel.setObjectName("heartRateLabel")
        self.gridLayout_2.addWidget(self.heartRateLabel, 5, 0, 1, 1)
        self.genderComboBox = QtWidgets.QComboBox(self.widget)
        self.genderComboBox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.genderComboBox.setStyleSheet("QComboBox{\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: grey;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::drop-down \n"
"{\n"
"    border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(../logo/down_arrow.png);\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}")
        self.genderComboBox.setIconSize(QtCore.QSize(16, 16))
        self.genderComboBox.setFrame(False)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logo/male_gender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.genderComboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../logo/female_gender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.genderComboBox.addItem(icon1, "")
        self.gridLayout_2.addWidget(self.genderComboBox, 4, 1, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.widget)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout_2.addWidget(self.surnameLabel, 1, 0, 1, 1)
        self.temperatureLabel = QtWidgets.QLabel(self.widget)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.gridLayout_2.addWidget(self.temperatureLabel, 7, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.widget)
        self.nameEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_2.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.surnameEdit = QtWidgets.QLineEdit(self.widget)
        self.surnameEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.surnameEdit.setObjectName("surnameEdit")
        self.gridLayout_2.addWidget(self.surnameEdit, 1, 1, 1, 1)
        self.tcEdit = QtWidgets.QLineEdit(self.widget)
        self.tcEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.tcEdit.setObjectName("tcEdit")
        self.gridLayout_2.addWidget(self.tcEdit, 2, 1, 1, 1)
        self.ageEdit = QtWidgets.QLineEdit(self.widget)
        self.ageEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.ageEdit.setObjectName("ageEdit")
        self.gridLayout_2.addWidget(self.ageEdit, 3, 1, 1, 1)
        self.heartRateEdit = QtWidgets.QLineEdit(self.widget)
        self.heartRateEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.heartRateEdit.setObjectName("heartRateEdit")
        self.gridLayout_2.addWidget(self.heartRateEdit, 5, 1, 1, 1)
        self.spO2Edit = QtWidgets.QLineEdit(self.widget)
        self.spO2Edit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.spO2Edit.setObjectName("spO2Edit")
        self.gridLayout_2.addWidget(self.spO2Edit, 6, 1, 1, 1)
        self.temperatureEdit = QtWidgets.QLineEdit(self.widget)
        self.temperatureEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.temperatureEdit.setObjectName("temperatureEdit")
        self.gridLayout_2.addWidget(self.temperatureEdit, 7, 1, 1, 1)
        self.diastolicBpEdit = QtWidgets.QLineEdit(self.widget)
        self.diastolicBpEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.diastolicBpEdit.setObjectName("diastolicBpEdit")
        self.gridLayout_2.addWidget(self.diastolicBpEdit, 8, 1, 1, 1)
        self.systolicBpEdit = QtWidgets.QLineEdit(self.widget)
        self.systolicBpEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.systolicBpEdit.setObjectName("systolicBpEdit")
        self.gridLayout_2.addWidget(self.systolicBpEdit, 9, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(manualEntryWindow)
        self.widget1.setGeometry(QtCore.QRect(12, 512, 491, 39))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.manualEntryEnterButton = QtWidgets.QPushButton(self.widget1)
        self.manualEntryEnterButton.clicked.connect(self.onEnterClicked)
        self.manualEntryEnterButton.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 150);\n"
"    border-style: inset;\n"
"}")
        self.manualEntryEnterButton.setObjectName("manualEntryEnterButton")
        self.gridLayout_5.addWidget(self.manualEntryEnterButton, 0, 1, 1, 1)
        self.manualEntryDiscardButton = QtWidgets.QPushButton(self.widget1)
        self.manualEntryDiscardButton.clicked.connect(self.onDiscardClicked)
        self.manualEntryDiscardButton.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 150);\n"
"    border-style: inset;\n"
"}")
        self.manualEntryDiscardButton.setObjectName("manualEntryDiscardButton")
        self.gridLayout_5.addWidget(self.manualEntryDiscardButton, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(manualEntryWindow)
        QtCore.QMetaObject.connectSlotsByName(manualEntryWindow)

    def retranslateUi(self, manualEntryWindow):
        _translate = QtCore.QCoreApplication.translate
        manualEntryWindow.setWindowTitle(_translate("manualEntryWindow", "Manual Entry"))
        self.nameLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.tcLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">T.C. No:</span></p></body></html>"))
        self.diastBPLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Diastolic Blood Pressure:</span></p></body></html>"))
        self.spo2Label.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">sp0</span><span style=\" font-size:10pt; vertical-align:sub;\">2</span><span style=\" font-size:10pt;\">:</span></p></body></html>"))
        self.sysBPLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Systolic Blood Pressure:</span></p></body></html>"))
        self.ageLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Age:</span></p></body></html>"))
        self.genderLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Gender:</span></p></body></html>"))
        self.heartRateLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Heart Rate:</span></p></body></html>"))
        self.genderComboBox.setItemText(0, _translate("manualEntryWindow", "Select"))
        self.genderComboBox.setItemText(1, _translate("manualEntryWindow", "MALE"))
        self.genderComboBox.setItemText(2, _translate("manualEntryWindow", "FEMALE"))
        self.surnameLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Surname:</span></p></body></html>"))
        self.temperatureLabel.setText(_translate("manualEntryWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Temperature:</span></p></body></html>"))
        self.manualEntryEnterButton.setText(_translate("manualEntryWindow", "Enter"))
        self.manualEntryDiscardButton.setText(_translate("manualEntryWindow", "Discard"))
    def onEnterClicked(self):
        
        name = self.nameEdit.toPlainText()
        surname = self.surnameEdit.toPlainText()
        age = self.ageEdit.toPlainText()
        genderIndex = self.genderComboBox.currentIndex()
        # 0 DEĞERİ DEĞİŞTİRİLECEK
        if genderIndex == 0:
            gender = "MALE"
        if genderIndex == 1:
            gender = "MALE"
        if genderIndex == 2:
            gender = "FEMALE"
            
       
        tc = self.tcEdit.toPlainText()
        sp02 = self.spO2Edit.toPlainText()
        heartRate = self.heartRateEdit.toPlainText()
        temperature = self.temperatureEdit.toPlainText()
        systolicBP = self.systolicBpEdit.toPlainText()
        diastolicBp = self.diastolicBpEdit.toPlainText()
        
        
        hr = HttpRequest()
        hr.postEntry(name,surname,age,gender,tc,sp02,heartRate,
                            temperature,systolicBP,diastolicBp)
        
        self.close()
    def onDiscardClicked(self):
        self.nameEdit.clear()
        self.surnameEdit.clear()
        self.ageEdit.clear()
        self.genderComboBox.setCurrentIndex(0)
        self.tcEdit.clear()
        self.heartRateEdit.clear()
        self.spO2Edit.clear()
        self.temperatureEdit.clear()
        self.systolicBpEdit.clear()
        self.diastolicBpEdit.clear()