# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingLabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitingLabel(object):
    def setupUi(self, WaitingLabel):
        WaitingLabel.setObjectName("WaitingLabel")
        WaitingLabel.resize(575, 176)
        WaitingLabel.setMaximumSize(QtCore.QSize(575, 176))
        WaitingLabel.setStyleSheet("background-color: transparent;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WaitingLabel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WaitingLabel)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo/e-triage.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.setCentralWidget(self.label)
        self.retranslateUi(WaitingLabel)        
        QtCore.QMetaObject.connectSlotsByName(WaitingLabel)

    def retranslateUi(self, WaitingLabel):
        _translate = QtCore.QCoreApplication.translate
        WaitingLabel.setWindowTitle(_translate("WaitingLabel", "Form"))
class WaitingLabel(QtWidgets.QMainWindow,Ui_WaitingLabel):
    def __init__(self,parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
