# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        calendarWidgetStart = QtWidgets.QCalendarWidget()
        calendarWidgetStart.setStyleSheet(
                            # "QCalendarWidget QMenu  { alternate-background-color: rgb(128, 128, 128); }"
                            "QCalendarWidget QToolButton"
                            "{\n"
                            "color:black;\n"
                            "}\n"
                            # "QCalendarWidget QToolButton::hover\n"
                            # "{\n"
                            # "background-color : cyan;\n"
                            # "}\n"
                            # "QCalendarWidget QToolButton::pressed\n"
                            # "{\n"
                            # "background-color : blue;\n"
                            # "}\n"
                            )
        calendarWidgetEnd = QtWidgets.QCalendarWidget()
        calendarWidgetEnd.setStyleSheet(
                            # "QCalendarWidget QMenu  { alternate-background-color: rgb(128, 128, 128); }"
                            "QCalendarWidget QToolButton"
                            "{\n"
                            "color:black;\n"
                            "}\n"
                            # "QCalendarWidget QToolButton::hover\n"
                            # "{\n"
                            # "background-color : cyan;\n"
                            # "}\n"
                            # "QCalendarWidget QToolButton::pressed\n"
                            # "{\n"
                            # "background-color : blue;\n"
                            # "}\n"
                            )
        # self._windowName = windowName
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.resize(1031, 631)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GraphWindow.sizePolicy().hasHeightForWidth())
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GraphWindow.setWindowIcon(icon)
        GraphWindow.setSizePolicy(sizePolicy)
        GraphWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayoutWidget = QtWidgets.QWidget(GraphWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(11, 11, 1011, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout.addWidget(self.nameEdit)
        self.surnameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.surnameLabel.setObjectName("surnameLabel")
        self.horizontalLayout.addWidget(self.surnameLabel)
        self.surnameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.surnameEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.surnameEdit.setReadOnly(True)
        self.surnameEdit.setObjectName("surnameEdit")
        self.horizontalLayout.addWidget(self.surnameEdit)
        self.tcLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tcLabel.setObjectName("tcLabel")
        self.horizontalLayout.addWidget(self.tcLabel)
        self.tcEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tcEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.tcEdit.setReadOnly(True)
        self.tcEdit.setObjectName("tcEdit")
        self.horizontalLayout.addWidget(self.tcEdit)
        self.ageLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.horizontalLayout.addWidget(self.ageLabel)
        self.ageEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ageEdit.setStyleSheet("QLineEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.ageEdit.setReadOnly(True)
        self.ageEdit.setObjectName("ageEdit")
        self.horizontalLayout.addWidget(self.ageEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.manualEntryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.manualEntryButton.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 150);\n"
"    border-style: inset;\n"
"}")
        self.manualEntryButton.setObjectName("manualEntryButton")

        self.horizontalLayout.addWidget(self.manualEntryButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startDateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.startDateLabel.setObjectName("startDateLabel")
        self.horizontalLayout_2.addWidget(self.startDateLabel)
        self.startDateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.startDateEdit.setStyleSheet("QDateEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QDateEdit::drop-down \n"
"{\n"
"    border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
"}\n"
"QDateEdit::down-arrow {\n"
"    image: url(../logo/down_arrow.png);\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}")
        self.startDateEdit.setAccelerated(True)
        self.startDateEdit.setCalendarPopup(True)
        self.startDateEdit.setObjectName("startDateEdit")
        self.startDateEdit.setDate(QtCore.QDate.currentDate())
        self.startDateEdit.setCalendarWidget(calendarWidgetStart)
        self.horizontalLayout_2.addWidget(self.startDateEdit)
        self.editDateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.editDateLabel.setObjectName("editDateLabel")
        self.horizontalLayout_2.addWidget(self.editDateLabel)
        self.endDateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.endDateEdit.setStyleSheet("QDateEdit {\n"
"    background-color:  rgb(255,255,255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 0, 120);\n"
"    font: bold 14px;\n"
"    color: black;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QDateEdit::drop-down \n"
"{\n"
"    border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
"}\n"
"QDateEdit::down-arrow {\n"
"    image: url(../logo/down_arrow.png);\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}")
        self.endDateEdit.setAccelerated(True)
        self.endDateEdit.setCalendarPopup(True)
        self.endDateEdit.setObjectName("endDateEdit")
        self.endDateEdit.setDate(QtCore.QDate.currentDate())
        self.endDateEdit.setCalendarWidget(calendarWidgetEnd)
        self.horizontalLayout_2.addWidget(self.endDateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.graphTab = QtWidgets.QWidget()
        self.graphTab.setObjectName("graphTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.graphTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.graphTab)
        self.graphicsView.setStyleSheet("QScrollBar:vertical {           \n"
"                            border: 1px solid #999999;\n"
"                           background:white;\n"
"                            width:10px;    \n"
"                            margin: 0px 0px 0px 0px;\n"
"                        }\n"
"                       QScrollBar::handle:vertical {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120), stop:1 rgb(0,0,120));\n"
"                            min-height: 0px;\n"
"                        }\n"
"                        QScrollBar::add-line:vertical {\n"
"                           background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0px;\n"
"                          subcontrol-position: bottom;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"                        QScrollBar::sub-line:vertical {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0  rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0 px;\n"
"                          subcontrol-position: top;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"QScrollBar:horizontal {           \n"
"                            border: 1px solid #999999;\n"
"                           background:white;\n"
"                            width:10px;    \n"
"                            margin: 0px 0px 0px 0px;\n"
"                        }\n"
"                       QScrollBar::handle:horizontal {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120), stop:1 rgb(0,0,120));\n"
"                            min-height: 0px;\n"
"                        }\n"
"                        QScrollBar::add-line:horizontal {\n"
"                           background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0px;\n"
"                          subcontrol-position: bottom;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"                        QScrollBar::sub-line:horizontal {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0  rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0 px;\n"
"                          subcontrol-position: top;\n"
"                            subcontrol-origin: margin;\n"
"                        }")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.graphTab, "")
        self.tableTab = QtWidgets.QWidget()
        self.tableTab.setObjectName("tableTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tableTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableView = QtWidgets.QTableView(self.tableTab)
        self.tableView.setStyleSheet("QScrollBar:vertical {           \n"
"                            border: 1px solid #999999;\n"
"                           background:white;\n"
"                            width:10px;    \n"
"                            margin: 0px 0px 0px 0px;\n"
"                        }\n"
"                       QScrollBar::handle:vertical {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120), stop:1 rgb(0,0,120));\n"
"                            min-height: 0px;\n"
"                        }\n"
"                        QScrollBar::add-line:vertical {\n"
"                           background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0px;\n"
"                          subcontrol-position: bottom;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"                        QScrollBar::sub-line:vertical {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0  rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0 px;\n"
"                          subcontrol-position: top;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"QScrollBar:horizontal {           \n"
"                            border: 1px solid #999999;\n"
"                           background:white;\n"
"                            width:10px;    \n"
"                            margin: 0px 0px 0px 0px;\n"
"                        }\n"
"                       QScrollBar::handle:horizontal {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120), stop:1 rgb(0,0,120));\n"
"                            min-height: 0px;\n"
"                        }\n"
"                        QScrollBar::add-line:horizontal {\n"
"                           background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0 rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0px;\n"
"                          subcontrol-position: bottom;\n"
"                            subcontrol-origin: margin;\n"
"                        }\n"
"                        QScrollBar::sub-line:horizontal {\n"
"                            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop: 0  rgb(0,0,120), stop: 0.5 rgb(0,0,120),  stop:1 rgb(0,0,120));\n"
"                            height: 0 px;\n"
"                          subcontrol-position: top;\n"
"                            subcontrol-origin: margin;\n"
"                        }")
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setObjectName("tableView")
        self.gridLayout_4.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tableTab, "")
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 50)

        self.retranslateUi(GraphWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)
        



    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "GraphWindow"))
        self.nameLabel.setText(_translate("GraphWindow", "Name:"))
        self.surnameLabel.setText(_translate("GraphWindow", "Surname:"))
        self.tcLabel.setText(_translate("GraphWindow", "T.C. No:"))
        self.ageLabel.setText(_translate("GraphWindow", "Age:"))
        self.manualEntryButton.setText(_translate("GraphWindow", "Manual Entry"))
        self.startDateLabel.setText(_translate("GraphWindow", "Start Date:"))
        self.startDateEdit.setDisplayFormat(_translate("GraphWindow", "d/M/yyyy"))
        self.editDateLabel.setText(_translate("GraphWindow", "End Date:"))
        self.endDateEdit.setDisplayFormat(_translate("GraphWindow", "d/M/yyyy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphTab), _translate("GraphWindow", "Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tableTab), _translate("GraphWindow", "Table"))

    